### ISSUE TITLE
Index Definition Analyzer

### ISSUE THREAD

**Issue by davidjgonzalez** [chetanmeh/oakutils#1]
Getting a Server Error when uploading XML or JSON to Index Definition Analyzer.. waited a few mins between submissions.

Sample upload files...
- [content.xml.zip](https://github.com/chetanmeh/oakutils/files/204492/content.xml.zip)
- [index.json.zip](https://github.com/chetanmeh/oakutils/files/204493/index.json.zip)

**Comment by chetanmeh** [comment]
@davidjgonzalez Fixed the issue now (nodeType index being null was not handled) Can you try again now?

**Comment by davidjgonzalez** [comment]
The content.xml works, but the index.json still throws a server error!

**Comment by chetanmeh** [comment]
index.json file had an extra char ^ at start which makes the json as invalid. If that is removed then it gets processed fine

**Comment by davidjgonzalez** [comment]
Copy pate artifact, Works - closing.
